move img to my-component
angular-medellin/learn pull request #2
Opened 2017-11-07 20:29 UTC by ManuCastrillonM

2017-11-08 22:39 UTC, ltciro approved these changes

2017-11-09 16:30 UTC, ghost requested changes

2017-11-09 16:30 UTC, ltciro commented on src/app/my-component/my-component.component.ts
> +  add() {
@ManuCastrillonM  porfis cambialo aquí también.

2017-11-09 16:33 UTC, ManuCastrillonM commented on src/app/my-component/my-component.component.ts
> +  add() {
Listo!

2017-11-09 16:39 UTC, ghost approved these changes

2017-11-09 16:39 UTC, merged